sudo: required
os: linux
services:
  - docker

git:
  submodules: true

before_install:
  - docker pull vowpalwabbit/travis-base
script:
  - docker run -a STDOUT -v `pwd`:/reinforcement_learning -t vowpalwabbit/travis-base /bin/bash -c "cd /reinforcement_learning && chmod +x ./build-linux.sh && ./build-linux.sh"
