trigger:
- master
- 'releases/**'

pr:
- '*'

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: vowpalwabbit/rl-ubuntu-1604:0.6.0
  endpoint: DockerHub

steps:
- checkout: self
  submodules: true
- bash: ./.scripts/linux/build-vw-bp.sh
  displayName: Build C++ binary parser
- bash: ./.scripts/linux/test-vw-bp.sh
  displayName: Test C++ binary parser
- task: PublishTestResults@2
