trigger:
- master
- 'releases/**'

pr:
- '*'

pool:
  # name: Hosted VS2017
  demands: Cmd
  vmImage: 'windows-2016:20210719.0'

variables:
  VCPKG_ARCHIVE_DIR: $(LOCALAPPDATA)\vcpkg\archives
  configuration: Release
  platform: x64

steps:
- checkout: self
  submodules: recursive
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg' # Options: nugetOrg, customFeed, netShare
    versionSelector: 'latestStable' # Required when packageFeedSelector == NugetOrg || PackageFeedSelector == CustomFeed# Options: latestPreRelease, latestStable, specificVersion
    #testPlatformVersion: # Required when versionSelector == SpecificVersion
    #customFeed: # Required when packageFeedSelector == CustomFeed
    #username: # Optional
    #password: # Optional
    #netShare: # Required when packageFeedSelector == NetShare
- task: Cache@2
  inputs:
    key: 'vcpkg | archives'
    path: $(VCPKG_ARCHIVE_DIR)
    restoreKeys: |
      vcpkg | archives
  displayName: Cache vcpkg dependencies
- script: CALL .scripts/restore.cmd
  displayName: 'Restore dependencies'
  env:
    nugetPath: $(Build.SourcesDirectory)\.nuget\nuget.exe
  failOnStderr: true
- script: CALL .scripts/build.cmd
  displayName: 'Build rl.sln'
  env:
    nugetPath: $(Build.SourcesDirectory)\.nuget\nuget.exe
  failOnStderr: true
- script: CALL .scripts/test.cmd
  displayName: 'Run tests'
  env:
    nugetPath: $(Build.SourcesDirectory)\.nuget\nuget.exe
  failOnStderr: false
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/out/test/Release/x64/*.trx'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: target'
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)\out\target
    ArtifactName: target
  condition: succeededOrFailed()
