trigger:
- master
- 'releases/**'

pr:
- '*'

pool:
  vmImage: 'ubuntu-18.04'

container:
  image: vowpalwabbit/rl-ubuntu-1804:latest
  endpoint: DockerHub

steps:
- checkout: self
  submodules: true
- bash: ./.scripts/linux/build-vw-bp.sh
  displayName: Build C++ binary parser
- bash: ./.scripts/linux/unit-tests-vw-bp-valgrind.sh
  displayName: Run Unit Tests C++ binary parser with Valgrind
- task: PublishTestResults@2
