trigger:
- master
- 'releases/**'

pr:
- '*'

pool:
  vmImage: 'macOS-10.15'

steps:
- checkout: self
  submodules: true
- bash: .scripts/macos/restore.sh
  displayName: 'Restore dependencies'
- bash: .scripts/macos/build.sh
  displayName: 'Build'
- bash: .scripts/macos/test.sh
  displayName: 'Run tests'
- task: PublishTestResults@2
