trigger:
- master
- 'releases/**'

pr:
- '*'

pool:
  name: Hosted VS2017
  demands: Cmd

variables:
  VCPKG_ARCHIVE_DIR: $(LOCALAPPDATA)\vcpkg\archives
  configuration: Release
  platform: x64

steps:
- checkout: self
  submodules: recursive
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg' # Options: nugetOrg, customFeed, netShare
    versionSelector: 'latestStable' # Required when packageFeedSelector == NugetOrg || PackageFeedSelector == CustomFeed# Options: latestPreRelease, latestStable, specificVersion
    #testPlatformVersion: # Required when versionSelector == SpecificVersion
    #customFeed: # Required when packageFeedSelector == CustomFeed
    #username: # Optional
    #password: # Optional
    #netShare: # Required when packageFeedSelector == NetShare
- task: Cache@2
  inputs:
    key: 'vcpkg | archives'
    path: $(VCPKG_ARCHIVE_DIR)
    restoreKeys: |
      vcpkg | archives
  displayName: Cache vcpkg dependencies
- script: CALL .scripts/restore-vw-bp-deps.cmd
  displayName: 'Restore dependencies for vw binary parser'
  failOnStderr: true
- script: |
    ls C:/vcpkg/installed/x64-windows-static-md/debug/bin
  displayName: 'ls everything'
- script: CALL .scripts/build-vw-bp.cmd
  displayName: 'Build vw_binary_parser'
  failOnStderr: false
- script: CALL .scripts/test-vw-bp.cmd
  displayName: 'Run tests for vw binary parser'
  failOnStderr: false
