trigger:
- master
- 'releases/**'

pr:
- '*'

pool:
  vmImage: 'ubuntu-16.04'

container:
  image: vowpalwabbit/rl-ubuntu-1604:0.6.0
  endpoint: DockerHub

steps:
- checkout: self
  submodules: true
- bash: ./.scripts/linux/build.sh
  displayName: Build C++
- bash: ./.scripts/linux/test.sh
  displayName: Test C++
- task: PublishTestResults@2
