add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/fakeit)
add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/date)
add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/pybind11)

set(VW_INSTALL OFF CACHE BOOL "")
set(BUILD_TESTS OFF CACHE BOOL "")
set(BUILD_JAVA OFF CACHE BOOL "")
set(BUILD_PYTHON OFF CACHE BOOL "")
set(BUILD_DOCS OFF CACHE BOOL "")
set(WARNINGS OFF CACHE BOOL "")
add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/vowpal_wabbit EXCLUDE_FROM_ALL)
if (USE_ZSTD)
    add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/zstd/build/cmake EXCLUDE_FROM_ALL)
endif()
