name: AddressSanitizer

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test_with_sanitizers:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        preset: [vcpkg-asan-debug, vcpkg-ubsan-debug]
        exclude:
          # UBSan not supported by MSVC on Windows
          - { os: windows-latest, preset: vcpkg-ubsan-debug }
    runs-on: ${{ matrix.os }}
    name: asan.${{ matrix.os }}.${{ matrix.preset }}
    env:
      UBSAN_OPTIONS: "print_stacktrace=1"
      VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg_binary_cache
      RL_BUILD_EXTERNAL_PARSER: "On"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup MSVC Developer Command Prompt
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/get-cmake@latest
      - run: echo "VCPKG_COMMIT=$(git rev-parse :ext_libs/vcpkg)" >> $GITHUB_ENV
        shell: bash
      - run: mkdir -p ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
      - uses: actions/cache@v3
        env:
          cache-name: vcpkg-cache
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}/*
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('vcpkg.json') }}-${{ env.VCPKG_COMMIT }}"
      - uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          configurePreset: "${{ matrix.preset }}"
      - name: Build
        run: cmake --build build --target rltest binary_parser_unit_tests
      - name: Run unit tests
        run: |
          cd build
          ctest --verbose --output-on-failure
