name: AddressSanitizer

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test_with_sanitizers:
    strategy:
      fail-fast: false
      matrix:
        #os: [windows-latest, ubuntu-latest, macos-13]
        os: [ubuntu-latest, macos-13] # Temporarily remove windows asan
        preset: [vcpkg-asan-debug, vcpkg-ubsan-debug]
        exclude:
          # UBSan not supported by MSVC on Windows
          - { os: windows-latest, preset: vcpkg-ubsan-debug }
    runs-on: ${{ matrix.os }}
    name: asan.${{ matrix.os }}.${{ matrix.preset }}
    env:
      UBSAN_OPTIONS: "print_stacktrace=1"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: git -C ${{ github.workspace }}/ext_libs/vcpkg fetch --unshallow
      - name: Setup MSVC Developer Command Prompt
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: ilammy/msvc-dev-cmd@v1
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/ext_libs/vcpkg'
          vcpkgJsonGlob: "${{ github.workspace }}/vcpkg.json"
      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -DRL_BUILD_EXTERNAL_PARSER=On
      - name: Build
        run: cmake --build build --target rltest binary_parser_unit_tests
      - name: Run unit tests
        run: |
          cd build
          ctest --verbose --output-on-failure
