name: Build RLClientLib

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: rlclientlib.ubuntu18.04
    container:
      image: vowpalwabbit/rl-ubuntu-1804:latest
    runs-on: ubuntu-latest
    steps:
      # v1 must be used because newer versions require a node.js version that will not run on this old image.
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: ./.scripts/linux/build.sh
      - run: ./.scripts/linux/test.sh

  build-linux-valgrind:
    name: rlclientlib-valgrind.ubuntu18.04
    container:
      image: vowpalwabbit/rl-ubuntu-1804:latest
    runs-on: ubuntu-latest
    steps:
      # v1 must be used because newer versions require a node.js version that will not run on this old image.
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: ./.scripts/linux/build-valgrind.sh
      - run: ./.scripts/linux/unit-tests-valgrind.sh

  build-macos:
    name: rlclientlib.macos-11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./.scripts/macos/restore.sh
      - run: ./.scripts/macos/build.sh
      - run: ./.scripts/macos/test.sh

  build-windows:
    name: rlclientlib.windows-2019
    runs-on: windows-2019
    env:
      VCPKG_ROOT: ${{ github.workspace }}/ext_libs/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg_binary_cache
      steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1

      # Setup vcpkg cache
      - run: echo "VCPKG_COMMIT=$(git rev-parse :ext_libs/vcpkg)" >> $GITHUB_ENV
        shell: bash
      - run: mkdir -p ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
      - uses: actions/cache@v3
        env:
          cache-name: vcpkg-cache
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}/*
          key: ${{ env.cache-name }}-${{ github.workflow }}-${{ github.action }}-${{ hashFiles('vcpkg.json') }}-${{ env.VCPKG_COMMIT }}

      - run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.bat
      - run: ./.scripts/restore-cmake.cmd
      - run: ./.scripts/build-cmake.cmd
      - run: ./.scripts/test-cmake.cmd