
name: Build MacOS
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Restore dependencies
        shell: bash
        run: .scripts/macos/restore.sh
      - name: Build
        shell: bash
        run: .scripts/macos/build.sh
      - name: Test
        shell: bash
        run: .scripts/macos/test.sh
