name: Build Binary Parser

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

jobs:
  build-linux:
    name: binary_parser.ubuntu18.04
    container:
      image: vowpalwabbit/rl-ubuntu-1804:latest
    runs-on: ubuntu-latest
    steps:
      # v1 must be used because newer versions require a node.js version that will not run on this old image.
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: ./.scripts/linux/build-vw-bp.sh
      - run: ./.scripts/linux/test-vw-bp.sh

  build-linux-valgrind:
    name: binary_parser-valgrind.ubuntu18.04
    container:
      image: vowpalwabbit/rl-ubuntu-1804:latest
    runs-on: ubuntu-latest
    steps:
      # v1 must be used because newer versions require a node.js version that will not run on this old image.
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - run: ./.scripts/linux/build-vw-bp.sh
      - run: ./.scripts/linux/unit-tests-vw-bp-valgrind.sh

  build-macos:
    name: binary_parser.macos-11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./.scripts/macos/restore-vw-bp.sh
      - run: ./.scripts/macos/build-vw-bp.sh
      - run: ./.scripts/macos/test-vw-bp.sh

  build-windows:
    name: binary_parser.windows-2019
    runs-on: windows-2019
    env:
      VCPKG_ROOT: ${{ github.workspace }}/ext_libs/vcpkg
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1

      # Setup vcpkg cache
      - run: echo "VCPKG_COMMIT=$(git rev-parse :ext_libs/vcpkg)" >> $GITHUB_ENV
        shell: bash
      - run: mkdir -p ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        shell: bash
      - uses: actions/cache@v3
        env:
          cache-name: vcpkg-cache
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}/*
          key: ${{ env.cache-name }}-${{ github.workflow }}-${{ github.action }}-${{ hashFiles('vcpkg.json') }}-${{ env.VCPKG_COMMIT }}

      - run: ${{ env.VCPKG_ROOT }}/bootstrap-vcpkg.bat
      - run: ${{ env.SOURCE_DIR }}/.scripts/restore-vw-bp-deps.cmd
      - run: ${{ env.SOURCE_DIR }}/.scripts/build-vw-bp.cmd
      - run: ${{ env.SOURCE_DIR }}/.scripts/test-vw-bp.cmd
