name: Integration with latest VW

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 8 * * *"

jobs:
  LatestVW:
    container:
      image: vowpalwabbit/rl-ubuntu-1804:latest
    runs-on: ubuntu-latest
    steps:
      # v1 must be used because newer versions require a node.js version that will not run on this old image.
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Update VW to latest
        shell: bash
        run: |
          pushd ext_libs/vowpal_wabbit
          git pull origin master
          popd
      - name: Configure
        run: cmake -S . -B build -G Ninja  -Drlclientlib_BUILD_ONNXRUNTIME_EXTENSION=On -DFMT_SYS_DEP=ON -DSPDLOG_SYS_DEP=ON
      - name: Build
        run: cmake --build build --target all
      - name: Test
        run: |
          cd build
          ctest --verbose --output-on-failure