name: .NET Nugets

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build_nuget_dotnet:
    name: build-nuget-${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "windows-latest", runtime_id: "win-x64", vcpkg_target_triplet: "x64-windows-static" }
          - { os: "ubuntu-latest", runtime_id: "linux-x64", vcpkg_target_triplet: "x64-linux" }
          - { os: "macos-latest", runtime_id: "osx-x64", vcpkg_target_triplet: "x64-osx" }
    runs-on: ${{matrix.config.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup MSVC Developer Command Prompt
        if: ${{ startsWith(matrix.config.os, 'windows') }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install dotnet t4
        if: ${{ startsWith(matrix.config.os, 'windows') }}
        run: dotnet tool install --global dotnet-t4

      # Build .NET Core, all platforms
      - name: Configure .NET Core
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/ext_libs/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.config.vcpkg_target_triplet }}
          -DVCPKG_HOST_TRIPLET=${{ matrix.config.vcpkg_target_triplet }}
          -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
          -Drlclientlib_BUILD_DOTNET=On
          -Drlclientlib_DOTNET_USE_MSPROJECT=Off
          -DRL_NUGET_PACKAGE_VERSION="${{ steps.get_version.outputs.version }}"
          -DBUILD_FLATBUFFERS=Off
          -DRAPIDJSON_SYS_DEP=ON
          -DFMT_SYS_DEP=ON
          -DSPDLOG_SYS_DEP=ON
          -DVW_ZLIB_SYS_DEP=ON
          -DVW_BOOST_MATH_SYS_DEP=ON
          -DVW_BUILD_VW_C_WRAPPER=Off
          -DBUILD_TESTING=Off
          -DRL_OPENSSL_SYS_DEP=On
          -DRL_CPPRESTSDK_SYS_DEP=On

      - run: cmake --build build --config Release -t rl.net.native
      - if: ${{ startsWith(matrix.config.os, 'windows') }}
        run: |
          cmake --build build --config Release -t rl.net

      - if: ${{ startsWith(matrix.config.os, 'windows') }}
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: |
            build/binaries/rl.net.native.dll
            build/binaries/Rl.Net.dll

      - if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: build/bindings/cs/rl.net.native/librl.net.native.so

      - if: ${{ startsWith(matrix.config.os, 'osx') }}
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: build/bindings/cs/rl.net.native/librl.net.native.dylib


  package_nuget:
    needs: build_nuget_dotnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: artifacts
          path: artifacts
      - uses: actions/setup-dotnet@v3
      - run: |
          dotnet pack ../nuget/dotnet/dotnetcore.nuspec -p:RL_NUGET_PACKAGE_VERSION=0.1.0+$GITHUB_SHA -o nuget_output
        working-directory: artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: artifacts/nuget_output/

  test_nuget:
    needs: package_nuget
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "windows-latest", runtime_id: "win-x64" }
          - { os: "ubuntu-latest", runtime_id: "linux-x64" }
          - { os: "macos-latest", runtime_id: "osx-x64" }
    runs-on: ${{matrix.config.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist
      - uses: actions/setup-dotnet@v3
      - name: Install package
        run: |
          set +e
          cd nuget/dotnet/test
          dotnet add dotnetcore_nuget_test.csproj package VowpalWabbit.RL --version 0.1.0+$GITHUB_SHA --source "${{github.workspace}}/dist" --no-restore
          dotnet restore dotnetcore_nuget_test.csproj --runtime ${{matrix.config.runtime_id}} --source "${{github.workspace}}/dist"
          dotnet restore dotnetcore_nuget_test.csproj --runtime ${{matrix.config.runtime_id}}
      - name: Build and run test
        run: |
          cd nuget/dotnet/test
          dotnet build dotnetcore_nuget_test.csproj --runtime ${{matrix.config.runtime_id}} --output build --no-restore --self-contained
          ./build/dotnetcore_nuget_test
